# Generated by Django 5.2.3 on 2025-07-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("selling_points", models.TextField(blank=True, null=True)),
                ("product_age", models.CharField(max_length=100)),
                ("starting_bid", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="auction_images/")),
                ("premium_verification", models.BooleanField(default=False)),
                ("bank_account_linked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
