# Generated by Django 5.2.3 on 2025-07-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionmodel",
            old_name="title",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="auctionmodel",
            old_name="selling_points",
            new_name="unique_points",
        ),
    ]
