# Generated by Django 5.2.3 on 2025-07-09 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_rename_title_auctionmodel_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionmodel",
            name="date_of_auction",
            field=models.DateField(default=datetime.date(2025, 7, 10)),
        ),
        migrations.AddField(
            model_name="auctionmodel",
            name="time_of_auction",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
